# Generated by Django 5.0a1 on 2023-10-17 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кол-во воды в наличии')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('is_busy', models.BooleanField(default=False, verbose_name='Занят')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.customer', verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выручка за день')),
                ('bottles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.bottle', verbose_name='Кол-во воды в наличии')),
                ('customers', models.ManyToManyField(to='adminn.customer', verbose_name='Клиенты')),
                ('employees', models.ManyToManyField(to='adminn.employee', verbose_name='Сотрудники')),
                ('completed_orders', models.ManyToManyField(related_name='completed_order', to='adminn.order', verbose_name='История заказов')),
                ('current_orders', models.ManyToManyField(related_name='current_orders', to='adminn.order', verbose_name='Текущие заказы')),
            ],
        ),
    ]
